### PR TITLE
recommendfood 

### PR DESCRIPTION
**Pull request by DinhDaiDuong**

### CODE REVIEW

**Comment by DinhDaiDuong** [comment]
Để vào recommendfood thì ở màn hình home chỗ trending food bấm zô View all

**Comment by Kawaiibuta** [comment]
+Some API errors (teriyaki Chicken-1026.2,Honey Roasted,Utimate Chickpea noodle  .....)
+Add enter action when searching for food.

**Comment by DinhDaiDuong** [comment]
Fixed and Some API errors (teriyaki Chicken-1026.2,Honey Roasted,Utimate Chickpea noodle .....) because link of FoodAPI is DEAD.

**Comment by Kawaiibuta** [comment]
Complete.

**Pull request closed without merging**
