### PR TITLE
<Dev>: Add track run result + Sleep

### PR DESCRIPTION
**Pull request by Kawaiibuta**
- Add UI of track result (Unable to retrive data from background servie but retrieve from foreground service) and display track on GG map.
- Add Sleep Screen (prototype):
  + Clock.
  + Sleep arc.
  + Add Sleep schedule
  + No notification
  + No Recording

### CODE REVIEW

**Comment by Kawaiibuta** [comment]
can't delete Sleep schedule
expand and simplify error display.

**Comment by ManhHoDinh** [comment]
@Kawaiibuta  Run screens need in the correct workflow app, not show in the init app. 
I don't check how to show the run results. Can you write instruction for that?

**Comment by Kawaiibuta** [comment]
> @Kawaiibuta Run screens need in the correct workflow app, not show in the init app. I don't check how to show the run results. Can you write instruction for that?

You can start the run track process when clicks on the Start Now button from Homepage

**Comment by Kawaiibuta** [comment]
> can't delete Sleep schedule expand and simplify error display.

expand and simplyfy error are a display error. The function still execute as expected and the UI will not show error on production.
Delete Sleep fixed

**Comment by Kawaiibuta** [comment]
can't sign up and login

**Comment by Kawaiibuta** [comment]
complete, @ManhHoDinh please help me to merge pull requests.

**Pull request merged**
